add post a new comment
BBSharps/games-review-project-frontend pull request #5
Opened 2023-01-12 15:59 UTC by BBSharps

2023-01-12 17:04 UTC, Poonam-raj requested changes
Please make sure the user can't post a empty comment

I also want you to make sure a user can't post or click submit when the form is still submitting (you can test this by slowing your internet down in the browser and spamming the submit button when you submit a valid comment)

Make the PR again once you've made changes and ofc let me know if you have qs

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
> +            return <option>{user.username}</option>;
Please remember to add keys to your maps!

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
> +          <input
Please make this able to take a multiline input (you'll need a different element)

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
> +      </form>
THis could be extracted into its own component

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
> +        </form>
This could be its own component

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
> +          return <ReviewCommentCard comment={comment} />;
Please remember keys for maps

2023-01-12 17:04 UTC, Poonam-raj commented on src/elements/review_by_id.jsx
>            return <ReviewCommentCard comment={comment} />;
please remember keys for maps

2023-01-13 10:59 UTC, B7Bprog requested changes
Hey Billy, it's looking pretty good, but there's still an issue remaining. When axios throws an error, your error message is not displayed. Instead the submit button reappears without the textarea. (See screenshot below) I recommend to set up a state for errors and use that to render the page conditionally. 
(Regarding your textarea, please disable resizing.)

Once you've fixed these please feel free to merge. 👍 

<img width="437" alt="Screenshot 2023-01-13 at 10 51 03" src="https://user-images.githubusercontent.com/54496822/212304436-2d75b030-fa9c-40d5-ad66-3ccd1681cfb8.png">

2023-01-13 10:59 UTC, B7Bprog commented on src/elements/Submit-form.jsx
> +            setNewCommentInput("Sorry comment failed, please refresh the page");
This error message didn't make it to the screen.

2023-01-13 11:42 UTC, merged